### PR TITLE
Add ubuntu-core-desktop-init

### PR DESCRIPTION
**Pull request by sergio-costas**
This is needed to use ubuntu-core-desktop-init during the setup

### CODE REVIEW

**Comment by kenvandine** [comment]
Please also add that to the models

**Comment by sergio-costas** [comment]
Added in both places.

**Comment by sergio-costas** [comment]
@kenvandine It seems that the models must be signed...
```
Error: Error preparing image: cannot fetch and check prerequisites for the model assertion: cannot add assertion model (ubuntu-core-desktop-22-amd64-dangerous; series:16 brand-id:canonical): failed signature verification: openpgp: invalid signature: hash tag doesn't match
```

How can I do that?

**Comment by sergio-costas** [comment]
Ok, I found how to do it.

**Comment by sergio-costas** [comment]
Nope... still has an invalid signature :-(

**Comment by sergio-costas** [comment]
I think it's fixed.

**Review by kenvandine — CHANGES_REQUESTED** [review]
Please revert the changes to the .model files and revert the brand-id and authority-id changes in the .json files.  We'll submit the .json files to IS to have them return the signed models which we'll commit here.

**Review by kenvandine — APPROVED** [review]
Looks good!

**Comment by kenvandine** [comment]
This was merged along with the updated models in #56

**Pull request closed without merging**
