### PR TITLE
Added alsa ucm configs

### PR DESCRIPTION
**Pull request by guylamar2006**
Added ucm repo to support sound for Steam Deck and other devices.

### CODE REVIEW

**Comment by robert-ancell** [comment]
I think this makes sense - @jhenstridge any thoughts?

**Review by jhenstridge — COMMENTED** [review]
Including this configuration seems reasonable. But this change won't get it included in the installed system. Instead, we'd need a change in [`core-base-desktop`](https://github.com/canonical/core-base-desktop) (probably by changing `hooks/006-add-gdm.chroot`).

If you want to submit a PR there I'll approve it. If not, I can get the change merged myself.

**Comment by guylamar2006** [comment]
The pull request should enable sound for older devices with UCM. the 1.2.9 version has support for AMD audio devices, Steam Deck audio should work when mantic reaches LTS on April 2024 because mantic has the UCM files for AMD audio devices.

**Comment by guylamar2006** [comment]
https://github.com/canonical/core-base-desktop/pull/54(url)

I sent the pull request, had to wait a little bit after signing the CLA.

**Comment by kenvandine** [comment]
Thanks for submitting the change to core-base-desktop.  I'm going to close this one.

**Pull request closed without merging**
