### PR TITLE
Add default snaps

### PR DESCRIPTION
**Pull request by robert-ancell**

### CODE REVIEW

**Comment by robert-ancell** [comment]
@jhenstridge will need your signature.

**Comment by jhenstridge** [comment]
I've signed the model, and also marked the new snaps as optional. I'll wait for the CI to complete before going further. Two things to test before merging:

1. Are all the snaps on core22 yet? If not, they may fail to install if we don't also include `gnome-3-38-2004`.
2. Is the seed partition size set in the gadget snap large enough? ubuntu-image will happily create an image with a larger partition to fit all the listed snaps, but it will fail to unpack correctly.

(2) can be fixed in the Makefile. (1) will require modifying and re-signing the model.

**Review by jhenstridge — CHANGES_REQUESTED** [review]
Looks like our seed partition is too big with these changes:

```
$ parted pc.img print
WARNING: You are not superuser.  Watch out for permissions.
Model:  (file)
Disk /home/james/src/ubuntu/ubuntu-core-gdm-spike/tmp/pc.img: 8590MB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name         Flags
 1      1049kB  2097kB  1049kB               BIOS Boot    bios_grub
 2      2097kB  2909MB  2907MB  fat32        ubuntu-seed  boot, esp
```

I think we'll need to update the code in `Makefile` to set the seed partition size to 3000M instead of 2500M.

**Comment by robert-ancell** [comment]
Tested in QEMU and all these snaps seem to be correctly installed.

**Pull request merged**
